"""add_insights_tables_for_real_data

Revision ID: 32578c0e26e2
Revises: 8866e53e286b
Create Date: 2025-06-04 16:25:57.598903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32578c0e26e2'
down_revision: Union[str, None] = '8866e53e286b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_population_statistics_administrative_code'), table_name='population_statistics')
    op.drop_index(op.f('ix_population_statistics_reference_date'), table_name='population_statistics')
    op.drop_table('population_statistics')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('population_statistics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('administrative_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('reference_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('province', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('district', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('age_0_9_male', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('age_10_19_male', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('age_20_29_male', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('age_30_39_male', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('age_40_49_male', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('age_50_59_male', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('age_60_69_male', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('age_70_79_male', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('age_80_89_male', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('age_90_99_male', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('age_100_plus_male', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('age_0_9_female', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('age_10_19_female', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('age_20_29_female', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('age_30_39_female', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('age_40_49_female', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('age_50_59_female', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('age_60_69_female', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('age_70_79_female', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('age_80_89_female', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('age_90_99_female', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('age_100_plus_female', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_population', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_male', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_female', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('population_statistics_pkey'))
    )
    op.create_index(op.f('ix_population_statistics_reference_date'), 'population_statistics', ['reference_date'], unique=False)
    op.create_index(op.f('ix_population_statistics_administrative_code'), 'population_statistics', ['administrative_code'], unique=False)
    # ### end Alembic commands ###
