"""add business store table with proper models

Revision ID: 75c45e0a3101
Revises: 771c75d50891
Create Date: 2025-06-17 10:18:13.939629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75c45e0a3101'
down_revision: Union[str, None] = '771c75d50891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_stores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_number', sa.String(length=20), nullable=False),
    sa.Column('store_name', sa.String(length=200), nullable=False),
    sa.Column('business_code', sa.String(length=10), nullable=False),
    sa.Column('business_name', sa.String(length=100), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('jibun_address', sa.String(length=300), nullable=True),
    sa.Column('road_address', sa.String(length=300), nullable=True),
    sa.Column('sido_name', sa.String(length=50), nullable=False),
    sa.Column('sigungu_name', sa.String(length=50), nullable=False),
    sa.Column('dong_name', sa.String(length=50), nullable=False),
    sa.Column('building_name', sa.String(length=200), nullable=True),
    sa.Column('floor_info', sa.String(length=50), nullable=True),
    sa.Column('room_info', sa.String(length=50), nullable=True),
    sa.Column('open_date', sa.Date(), nullable=True),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('business_status', sa.String(length=20), nullable=False),
    sa.Column('standard_industry_code', sa.String(length=10), nullable=True),
    sa.Column('commercial_category_code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_stores_business_code'), 'business_stores', ['business_code'], unique=False)
    op.create_index(op.f('ix_business_stores_business_name'), 'business_stores', ['business_name'], unique=False)
    op.create_index(op.f('ix_business_stores_business_status'), 'business_stores', ['business_status'], unique=False)
    op.create_index(op.f('ix_business_stores_dong_name'), 'business_stores', ['dong_name'], unique=False)
    op.create_index(op.f('ix_business_stores_latitude'), 'business_stores', ['latitude'], unique=False)
    op.create_index(op.f('ix_business_stores_longitude'), 'business_stores', ['longitude'], unique=False)
    op.create_index(op.f('ix_business_stores_sido_name'), 'business_stores', ['sido_name'], unique=False)
    op.create_index(op.f('ix_business_stores_sigungu_name'), 'business_stores', ['sigungu_name'], unique=False)
    op.create_index(op.f('ix_business_stores_store_name'), 'business_stores', ['store_name'], unique=False)
    op.create_index(op.f('ix_business_stores_store_number'), 'business_stores', ['store_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_stores_store_number'), table_name='business_stores')
    op.drop_index(op.f('ix_business_stores_store_name'), table_name='business_stores')
    op.drop_index(op.f('ix_business_stores_sigungu_name'), table_name='business_stores')
    op.drop_index(op.f('ix_business_stores_sido_name'), table_name='business_stores')
    op.drop_index(op.f('ix_business_stores_longitude'), table_name='business_stores')
    op.drop_index(op.f('ix_business_stores_latitude'), table_name='business_stores')
    op.drop_index(op.f('ix_business_stores_dong_name'), table_name='business_stores')
    op.drop_index(op.f('ix_business_stores_business_status'), table_name='business_stores')
    op.drop_index(op.f('ix_business_stores_business_name'), table_name='business_stores')
    op.drop_index(op.f('ix_business_stores_business_code'), table_name='business_stores')
    op.drop_table('business_stores')
    # ### end Alembic commands ###
