"""add username field

Revision ID: bff2ba2df7b3
Revises: cc1d418c37d9
Create Date: 2025-05-31 16:38:47.695374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bff2ba2df7b3'
down_revision: Union[str, None] = 'cc1d418c37d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('users_id', sa.String(length=36), nullable=False),
    sa.Column('business_name', sa.String(length=100), nullable=False),
    sa.Column('business_registration_number', sa.String(length=20), nullable=False),
    sa.Column('business_type', sa.String(length=50), nullable=False),
    sa.Column('business_category', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('representative_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_registration_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_profiles')
    # ### end Alembic commands ###
