version: '3.8'

# 개발환경용 Docker Compose
# 핫 리로드와 디버깅을 지원하는 개발 환경

services:
  # PostgreSQL 데이터베이스 (운영환경과 동일)
  postgres:
    image: pgvector/pgvector:pg17
    container_name: marketing_platform_db_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-marketing_platform_dev}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres123}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d/
    ports:
      - "5433:5432"  # 운영환경과 포트 분리
    networks:
      - marketing_dev_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-marketing_platform_dev}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis 캐시 (개발환경)
  redis:
    image: redis:7-alpine
    container_name: marketing_platform_cache_dev
    restart: unless-stopped
    ports:
      - "6380:6379"  # 운영환경과 포트 분리
    networks:
      - marketing_dev_network

  # 백엔드 개발 서버 (핫 리로드)
  backend-dev:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: marketing_platform_api_dev
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres123}@postgres:5432/${POSTGRES_DB:-marketing_platform_dev}
      REDIS_URL: redis://redis:6379/0
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      DEBUG: true
      SECRET_KEY: dev-secret-key
      ALLOWED_ORIGINS: http://localhost:3000,http://localhost:5173
    volumes:
      - ./backend:/app  # 소스 코드 마운트 (핫 리로드)
      - ./logs:/app/logs
    ports:
      - "8001:8000"  # 운영환경과 포트 분리
    depends_on:
      - postgres
      - redis
    networks:
      - marketing_dev_network

  # PostgreSQL MCP Server (개발환경)
  mcp-server-dev:
    build:
      context: ./mcp-server
      dockerfile: Dockerfile
    container_name: marketing_platform_mcp_dev
    restart: unless-stopped
    environment:
      # 데이터베이스 연결 설정
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB:-marketing_platform_dev}
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-postgres123}
      DB_SSL: false
      
      # MCP 서버 설정
      MCP_SERVER_HOST: 0.0.0.0
      MCP_SERVER_PORT: 3001
      
      # 개발환경 설정
      LOG_LEVEL: debug
      DEBUG: true
      MAX_CONNECTIONS: 5
      CONNECTION_TIMEOUT: 10000
    volumes:
      - ./mcp-server:/app  # 소스 코드 마운트 (개발용)
      - /app/node_modules  # node_modules 볼륨 마운트
    ports:
      - "3002:3001"  # 운영환경과 포트 분리
    depends_on:
      - postgres
    networks:
      - marketing_dev_network
    command: npm run dev  # 개발 모드로 실행

  # 데이터베이스 관리 도구
  adminer:
    image: adminer:latest
    container_name: marketing_platform_adminer_dev
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - marketing_dev_network

# 개발환경 네트워크
networks:
  marketing_dev_network:
    driver: bridge
    name: marketing_platform_dev_network

# 개발환경 볼륨
volumes:
  postgres_dev_data:
    name: marketing_platform_postgres_dev_data
